name: pydsft
channels:
  - conda-forge
  - defaults
dependencies:
  - dnspython=2.1.0
  - imageio=2.9.0
  - ipython=7.25.0
  - ipywidgets=7.6.3
  - jupyterlab=3.0.16
  - jupyterlab_widgets=1.0.0
  - matplotlib=3.4.2
  - nltk=3.6.2
  - nodejs=16.4.1
  - numpy=1.21.1
  - pandas=1.3.0
  - pip=21.1.3
  - pymongo=3.12.0
  - python=3.8.10
  - scikit-learn=0.24.2
  - scipy=1.7.0
  - seaborn=0.11.1
  - spacy=3.1.1
  - sqlite=3.36.0
  - statsmodels=0.12.2
  - tensorflow
  - widgetsnbextension=3.5.1
  - pip:
    - dweepy==0.3.0
    - en-core-web-lg==3.0.0
    - en-core-web-md==3.1.0
    - en-core-web-sm==3.0.0
    - folium==0.12.1
    - geopy==2.2.0
    - ibm-watson
    - pubnub==5.0.1
    - pydub==0.25.1
    - textblob>=0.17.0
    - tweepy==4.3.0
    - tweet-preprocessor==0.6.0
    - wordcloud==1.8.1
